version: "3.8"
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            # KAFKA_LISTENERS: PLAINTEXT://:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            # KAFKA_CREATE_TOPICS: "kafka-chat:1:1"
            # KAFKA_ADVERTISED_LISTENERS: kafka:9092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    client:
        build: 
            context: "./kafka-chat-ui"
            dockerfile: Dockerfile 
        ports: 
            - "3000:3000"
    app:
        build:
            context: "./chat"
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - mysql
            - kafka
        ports:
            - "9090:9090"
        environment:
            - TZ=Asia/Seoul

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
        - 3307:3306 # 포트 변경
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: 1004
            TZ: Asia/Seoul
        volumes:
        - ./db/mysql/data:/var/lib/mysql
        - ./db/mysql/init:/docker-entrypoint-initdb.d
        platform: linux/x86_64
