version: "3.8"
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    client1:
        build: 
            context: "./client1"
            dockerfile: Dockerfile 
        restart: on-failure
        ports: 
            - "3000:3000"
    server1:
        build:
            context: "./server1"
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        ports:
            - "9100:9100"
        environment:
            - TZ=Asia/Seoul
    client2:
        build: 
            context: "./client2"
            dockerfile: Dockerfile 
        restart: on-failure
        ports: 
            - "3001:3001"
    server2:
        build:
            context: "./server2"
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        ports:
            - "9101:9101"
        environment:
            - TZ=Asia/Seoul