version: "3.8"
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            # KAFKA_LISTENERS: PLAINTEXT://:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            # KAFKA_CREATE_TOPICS: "kafka-chat:1:1"
            # KAFKA_ADVERTISED_LISTENERS: kafka:9092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    client:
        build: 
            context: "./kafka-chat-ui"
            dockerfile: Dockerfile 
        restart: on-failure
        ports: 
            - "3000:3000"
    app:
        build:
            context: "./chat"
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - kafka
        ports:
            - "9100:9100"
        environment:
            - TZ=Asia/Seoul
